// <auto-generated/>
namespace DeepClone.SourceGenerator;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("DeepClone.SourceGenerator", "1.0.0.0")]
[global::System.AttributeUsageAttribute(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
internal sealed class DeepCloneableAttribute : global::System.Attribute { }