// <auto-generated/>
namespace DeepClone.SourceGenerator.UnitTests;

internal partial class MyInternalClass
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DeepClone.SourceGenerator", "1.0.0.0")]
    public MyInternalClass DeepClone() =>
        new()
        {
        };
}