// <auto-generated/>
namespace DeepClone.SourceGenerator.UnitTests;

public partial class MyNestedClass
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DeepClone.SourceGenerator", "1.0.0.0")]
    public MyNestedClass DeepClone() =>
        new()
        {
            NestedInt = this.NestedInt,
            NestedString = this.NestedString
        };
}