// <auto-generated/>
namespace DeepClone.SourceGenerator.UnitTests;

public partial class MyRecursiveClass
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DeepClone.SourceGenerator", "1.0.0.0")]
    public MyRecursiveClass DeepClone() =>
        new()
        {
            MyInt = this.MyInt,
            MyString = this.MyString,
            MyRecursiveClass = this.MyRecursiveClass?.DeepClone()
        };
}