// <auto-generated/>
namespace DeepClone.SourceGenerator.UnitTests;

public partial class MyRootClass
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DeepClone.SourceGenerator", "1.0.0.0")]
    public MyRootClass DeepClone() =>
        new()
        {
            Int = this.Int,
            String = this.String,
            NestedClass = this.NestedClass?.DeepClone()
        };
}