namespace DeepClone.SourceGenerator.Constants;

using System.Reflection;

internal static class SourceCode
{
    public static readonly string GeneratedCodeAttribute = $@"[global::System.CodeDom.Compiler.GeneratedCodeAttribute(""{Assembly.GetExecutingAssembly().GetName().Name}"", ""{Assembly.GetExecutingAssembly().GetName().Version}"")]";

    public static readonly string DeepCloneableAttribute = $$"""
        // <auto-generated/>
        namespace JackHenry.JHAContractTypes;

        {{GeneratedCodeAttribute}}
        [global::System.AttributeUsageAttribute(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
        internal sealed class {{nameof(DeepCloneableAttribute)}} : global::System.Attribute
        {
        }
        """;
}